import Head from 'next/head';
import Header from '../components/Header';
import Hero from '../components/Hero';
import Portfolio from '../components/Portfolio';
import Services from '../components/Services';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dimitri Portfolio</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <Header />

      <Hero />

      <Services />

      <Portfolio />
    </div>
  );
}
